name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Setup Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@0a35821d5c230e903fcfe077583637dea1b27b47 # v9.0.0
        with:
          version: v2.6.2

      - name: Run make test
        run: go test -v ./...

      - name: Get PR version
        id: pr_version
        run: echo "version=$(grep '^VERSION :=' Makefile | cut -d' ' -f3)" >> $GITHUB_OUTPUT

      - name: Checkout main branch
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          ref: main
          path: main

      - name: Get main version
        id: main_version
        run: echo "version=$(grep '^VERSION :=' main/Makefile | cut -d' ' -f3)" >> $GITHUB_OUTPUT

      - name: Compare versions
        run: | #shell
          PR_VERSION="${{ steps.pr_version.outputs.version }}"
          MAIN_VERSION="${{ steps.main_version.outputs.version }}"
          echo "PR version: $PR_VERSION"
          echo "Main version: $MAIN_VERSION"
          if [ "$PR_VERSION" = "$MAIN_VERSION" ]; then
            echo "Error: Makefile VERSION in PR is the same as in main branch."
            exit 1
          fi
          # Using sort -V for version comparison
          LATEST_VERSION=$(printf "%s\n%s" "$PR_VERSION" "$MAIN_VERSION" | sort -V | tail -n1)
          if [ "$LATEST_VERSION" != "$PR_VERSION" ]; then
            echo "Error: Makefile VERSION in PR is not greater than in main branch."
            exit 1
          fi
          echo "Version check passed."
